version: "3.8"

services:
  web:
    build:
      context: ./fiap-farms-dashboard
    image: vfornazi/fiap-farms-dashboard:latest
    container_name: fiap-farms-web
    ports:
      - "5173:80"
    restart: unless-stopped

  web-login:
    build:
      context: ./fiap-farms-web-login
    image: vfornazi/fiap-farms-web-login:latest
    container_name: fiap-farms-web-login
    ports:
      - "5174:80"  
    restart: unless-stopped

  mobile:
    build:
      context: ./fiap-farms-mobile
    image: vfornazi/fiap-farms-mobile:latest
    container_name: fiap-farms-mobile
    ports:
      - "8081:8081"   # Metro Bundler
      - "19000:19000" # Expo Go (App)
      - "19001:19001" # Expo DevTools
    environment:
      - WEB_DASHBOARD_URL=http://host.docker.internal:5173
    stdin_open: true 
    tty: true  
    restart: unless-stopped
